on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    name: test-build
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
          chmod +x build.bash
          ./build.bash

    - uses: actions/upload-artifact@v4
      with:
        name: test-Files
        path: Release/**